blob.server.port: 6124
taskmanager.memory.process.size: 8g
metrics.reporter.prom.port: 9249
slotmanager.number-of-slots.min: 25
metrics.scope.operator: <job_id>.<task_id>.<subtask_index>.<operator_name>
jobmanager.rpc.address: jobmanager
metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
metrics.scope.task: <job_id>.<task_id>.<subtask_index>
jobmanager.memory.process.size: 1600m
state.savepoints.dir: file:///opt/flink/savepoints
jobmanager.rpc.port: 6123
query.server.port: 6125
metrics.scope.tm: <host>.<tm_id>
state.checkpoint-storage: filesystem
parallelism.default: 4
taskmanager.numberOfTaskSlots: 5
cluster.fine-grained-resource-management.enabled: false
cluster.evenly-spread-out-slots: false
state.backend: hashmap
state.checkpoints.dir: file:///opt/flink/checkpoints
taskmanager.resource-id: tm_20c_4
taskmanager.resource-id: tm_20c_4
taskmanager.resource-id: tm_20c_4
taskmanager.resource-id: tm_20c_4
taskmanager.resource-id: tm_20c_4
taskmanager.resource-id: tm_20c_4
taskmanager.resource-id: tm_20c_4
taskmanager.resource-id: tm_20c_4
taskmanager.resource-id: tm_20c_4
taskmanager.resource-id: tm_20c_4
taskmanager.resource-id: tm_20c_4
taskmanager.resource-id: tm_20c_4
taskmanager.resource-id: tm_20c_4
taskmanager.resource-id: tm_20c_4
taskmanager.resource-id: tm_20c_4
taskmanager.resource-id: tm_20c_4
taskmanager.resource-id: tm_20c_4
taskmanager.resource-id: tm_20c_4
taskmanager.resource-id: tm_20c_4
taskmanager.resource-id: tm_20c_4
taskmanager.resource-id: tm_20c_4
taskmanager.resource-id: tm_20c_4
taskmanager.resource-id: tm_20c_4
taskmanager.resource-id: tm_20c_4
taskmanager.resource-id: tm_20c_4
taskmanager.resource-id: tm_20c_4
